import java.util.Random;
import java.util.Scanner;
class glaciers{
    public static void main(String[] args){
        Random rand = new Random();
        Scanner user = new Scanner(System.in);
        String[][] x = new String[300][2];
        int length=83;
        int[] z = new int[length];
        int r;
        int temp;
        for(int i=0; i<length; i++){
            z[i]=i;
        }
        for(int i=0; i<length; i++){
            r = rand.nextInt(length);
            temp = z[i];
            z[i] = z[r];
            z[r] = temp;
        }
        x[0][0] = "Glacier"; x[0][1] = "a mass of ice and granular snow formed by compaction & recrystallization of snow, laying largely or wholly on land and showing evidence of past or present movement.";
        x[1][0] = "digenetic?"; x[1][1] = "";
        x[2][0] = "ice is a mineral"; x[2][1] = "";
        x[3][0] = "2 glaciers on antarctica seperated by a mountain range"; x[3][1] = "";
        x[4][0] = "the west antarctic glacier is melting faster than the eastern one"; x[4][1] = "";
        x[5][0] = "the north pole is just ice ontop of ocean"; x[5][1] = "";
        x[6][0] = "glacier"; x[6][1] = "a large, long-lasting mass of ice, formed on land that moves under the influence of gravity and its own weight";
        x[7][0] = "alpine glaciation"; x[7][1] = "found in mountainous regions, act more like rivers";
        x[8][0] = "continental glaciation"; x[8][1] = "exists where a large part of a continent is covered by glacial ice, act more like a puddle";
        x[9][0] = "Glaciers develop where all of annual snow doesn’t melt away in summer"; x[9][1] = "Polar regions, Heavy winter snowfall, High elevations, 85% in Antarctica, 10% in Greenland";
        x[10][0] = "Modern Glacier Distribution"; x[10][1] = "Mostly limited to Polar Regions, Northern Hemisphere Sea Ice Pack is seasonal and ephemeral, Greenland Ice Sheet is “permanent” (10%), Antarctic Ice Sheet is “permanent” (85%), Remaing Alpine glaciers amount to only 5%,";
        x[11][0] = "Most of the Earth’s freshwater is bound up in"; x[11][1] = "Antarctic Ice Sheet, ~2 % of total global water budget";
        x[12][0] = "Dr. Rayburn’s secrete ingredients for making glaciers:"; x[12][1] = "Land, Snow, Cold Summers, Gravity, Time";
        x[13][0] = "Formation and Growth of Glaciers"; x[13][1] = "A new snowfall may be in the form of light “powder snow,” which consists mostly of air trapped between many six-pointed snowflakes.  In a short time the snowflakes settle by compaction under their own weight and much of the air between them is driven out.  This eventually forms glacier ice.";
        x[14][0] = "warm ocean currents feed glaciers more snow"; x[14][1] = "";
        x[15][0] = "Snow to Ice"; x[15][1] = "Snowflakes > Granular snow > firn > glacier ice. diagenetic process?";
        x[16][0] = "how deep does the shit have to be to compress into glacial ice?"; x[16][1] = "depends on the temperature of your location, different locations in different glaciers have different depths to the current ice boundary.";
        x[17][0] = "you hit the firn ice boundary generally at "; x[17][1] = "70 or 80 m depth";
        x[18][0] = "the density of ice is .9?"; x[18][1] = "";
        x[19][0] = "ice is in the ____ crystal system"; x[19][1] = "hexagonal, it shears a long to the side like shearing a deck of cards";
        x[20][0] = "Intergranular Shifting"; x[20][1] = "Differential movement between ice grains";
        x[21][0] = "Intragranular Shifting"; x[21][1] = "Deformation along crystal axial plane";
        x[22][0] = "Recrystallization"; x[22][1] = "Melting and refreezing of ice crystals";
        x[23][0] = "ice can recrystallize around a ruck underneath the glacier"; x[23][1] = "the ice will turn into water to get around the rock.";
        x[24][0] = "warm based glacier movement"; x[24][1] = "there is water at the bottom that allows the ice to slide along the base.";
        x[25][0] = "cold based glacier movement"; x[25][1] = "the glacier is frozen to the underlying rock and moves primarily by shear deformation or intragranular shifting";
        x[26][0] = "positive budget, negative budget"; x[26][1] = "if, over a period of time, the amount of snow a glacier gains is greater than the amount of ice and water it loses, the glacier’s budget is positive if it expands, if the opposite occurs the glacier’s budget is negative ";
        x[27][0] = "advancing glaciers:"; x[27][1] = "glaciers with positive budgets that push outward and downward at their edges";
        x[28][0] = "receding glaciers:"; x[28][1] = "glaciers with negative budgets that grow smaller and their edges melt back";
        x[29][0] = "zone of accumulation"; x[29][1] = "the upper part of the glacier with a perennial snow cover";
        x[30][0] = "zone of wastage/ablation:"; x[30][1] = "the lower part of the glacier where ice is lost, or wasted, by melting, evaporation, sublimation and calving.";
        x[31][0] = "snow line:"; x[31][1] = "the boundary between these two altitudinal zones of a glacier is an irregular line; marks the highest point at which the glacier’s winter snow cover is lost during a melt season";
        x[32][0] = "terminus:"; x[32][1] = "the lower edge of a glacier which moves farther downvalley when a valley glacier has a positive budget, sediment drops, when there is a neutral budget it will leave a pile of stuff.";
        x[33][0] = "there is a meltwater stream that begins at the"; x[33][1] = "terminus where water is melting";
        x[34][0] = "nunatak"; x[34][1] = "mountain range rising above ice surface";
        x[35][0] = "ablation/wasted:"; x[35][1] = "under the influence of gravity, glacier ice moves downward and is eventually lost or wasted";
        x[36][0] = "icebergs:"; x[36][1] = "a block of glacier-derived ice floating in water";
        x[37][0] = "Glacier Classification"; x[37][1] = "Thermal (temperature of the ice relative to Pressure Melting Point), Morphology (ice profile and topography), Dynamics (mass balance)";
        x[38][0] = "Temperate Glacier"; x[38][1] = "(thermal) the ice is at or near the pressure melting point. wet based glacier, can slide across the land.";
        x[39][0] = "polar glacier"; x[39][1] = "(thermal) cold based glacier where ice is below the pressure melting point, but its possible that its seasonally wet at the bottom, but the rest of the time its shear deformation.";
        x[40][0] = "Sub-Polar glacier "; x[40][1] = "(thermal) ice is always below PMP -> “frozen based glaciers”";
        x[41][0] = "Alpine glacier"; x[41][1] = "(Morphology) controlled by topography, like a river";
        x[42][0] = "Ice Sheet or Ice Cap Glacier"; x[42][1] = "(Morphology) Independent of topography, continental glacier";
        x[43][0] = "Piedmont glacier:"; x[43][1] = "(Morphology) Alpine glacier that flows onto flat area and spreads out";
        x[44][0] = "Advancing glacier:"; x[44][1] = "(Dynamics)(positive mass balance)";
        x[45][0] = "Stagnating glacier:"; x[45][1] = "(Dynamics)(negative mass balance)";
        x[46][0] = "Neutral glacier:"; x[46][1] = "(Dynamics)(equilibrium mass balance)";
        x[47][0] = "Movement of Valley Glaciers"; x[47][1] = "valley glaciers move downslope under the influence of gravity and their own weight, the rate being variable, ranging from less than a few millimeters a day to more than 15 meters a day glaciers in temperate climates - where the temperature is at or near the melting point for ice - tend to move faster than those in colder regions - where the ice temperature stays well below freezing";
        x[48][0] = "basal sliding:"; x[48][1] = "the sliding of the glacier as a single body over the underlying rock";
        x[49][0] = "plastic flow:"; x[49][1] = "movement that occurs within the glacier due to the plastic or “deformable” nature of the ice itself";
        x[50][0] = "rigid zone:"; x[50][1] = "the upper part of the glacier that has brittle deformation, creating cravasses. The cravasses only go down as far as the rigid zone goes";
        x[51][0] = "when ice flows, there is brittle deformation above a certain point and plastic deformation below. for plastic deformation, there needs to be enough pressure of the material above."; x[51][1] = "";
        x[52][0] = "as you force ice around boundaries, there can be different stress on different points of the ice"; x[52][1] = "this causes the cravasses, as the glacier goes around a bend or over a nick point";
        x[53][0] = "Fastest ice motion occurs at the surface near the center of the glacier (least amount of frictional drag)."; x[53][1] = "";
        x[54][0] = "Ogives"; x[54][1] = "bedrock controlled, the ogives begins where there is a break in slope. during the summer, the ice melts quicker where it is thinner which is over slopes. dirt collects at the bottom of the slopes after it comes out of the melted ice n shit u kno what I mean. this happens yearly and the ogives bend as the ice river moves forward.";
        x[55][0] = "t(tao) = p(rho)gt sin(a)"; x[55][1] = "tao is stress on the ice. ro is the ice density, g is gravity, t is the ice thickness, sin(alpha) is ice slope";
        x[56][0] = "Ogives long explanation"; x[56][1] = "Alternating bands of light and dark ice that form a series of ridges and swales at the base of some ice falls. The arcuate bands bend down-glacier due to the faster flow in the center of the glacier than along the sides of the valley walls. The dark bands represent ice that moved over the fall during the summer season when more melting occurs and form swales. The light bands represent ice that moved over the fall during the winter season when little or no melting occurs and form ridges.";
        x[57][0] = "with ice, if the slope is higher, the ice is "; x[57][1] = "thinner and vice versa";
        x[58][0] = "crevasses:"; x[58][1] = "open fissures in a glacier caused when the glacier passes over a steep part of the valley floor and moves faster than the upper part of the ridge zone of ice which cannot stretch to move as rapidly as the underlying ice.  Being brittle, the ice of the rigid zone is broken by the tensional forces";
        x[59][0] = "radial cravasses"; x[59][1] = "the ice moves and spreads out, causing cravasses parallel to movement.";
        x[60][0] = "longitudinal cravasses"; x[60][1] = "ice spreads out only kinda, causing cravasses parallel to movement.";
        x[61][0] = "transverse cravasses"; x[61][1] = "ice goes over a change in slope or a nickpoint causing perpendicular cravasses";
        x[62][0] = "chevron cravasses"; x[62][1] = "cravasses that form from shear stress as the valley becomes thinner, the cravasses form seemingly diagonal upstream, kinda looks like they should be going diagonal to the left due to how the ice moves slower along the sides but idk.";
        x[63][0] = "compressive flow"; x[63][1] = "as ice flows over a break in slope, rotating reverse faults can occur in the ice. since these extend all the way to the bottom, the ice is very thin.";
        x[64][0] = "extending flow"; x[64][1] = "as ice flows over an increasing slope, it can form normal faults. since these extend all the way to the bottom, the ice is very thin.";
        x[65][0] = "why might there be snow in the cravasses?"; x[65][1] = "the snow doesn't melt easily because the sunlight gets blocked inside the cravass";
        x[66][0] = "if there is fractures in the rock below the glacier and seasons are a thing, we can create"; x[66][1] = "freeze thaw weathering in the joints, eroding the rock out and the glacier picks it up and drags it along";
        x[67][0] = "if there is fractures in the rock below the glacier, the glacier can freeze to the rocks and"; x[67][1] = "pluck n shit";
        x[68][0] = "if there is bedrock sticking up in the glacier underneath"; x[68][1] = "pressure on the side facing the current causes the ice to melt and then freeze on the other side of the rock, which plucks bits and pieces off the rock, causing an asymetrical land form.";
        x[69][0] = "faceted:"; x[69][1] = "given a flat surface by abrasion";
        x[70][0] = "striations:"; x[70][1] = "scratches in the rock in the direction of ice movement";
        x[71][0] = "rock flour:"; x[71][1] = "a powder of fine fragments produced by the grinding of rock across rock ";
        x[72][0] = "Under glacier erosion"; x[72][1] = "Abrasion & plucking, Bedrock polished & striated, Rock flour washes out of glacier, Polishing and rounding, Striations-  scratches & grooves on rock, ";
        x[73][0] = "Above glacier erosion"; x[73][1] = "Frost wedging takes place, Erosion by glaciers steepens slopes";
        x[74][0] = "Lunate Fracture or crescentic gouge"; x[74][1] = "the shits that tells you where the ice is moving, the rock digs in. higher slope is in direction of movement";
        x[75][0] = "chatter marks"; x[75][1] = "ice pulls on rock bed and causes crescent shaped fractures";
        x[76][0] = "there is a huge layer of ice over a mountain, the ice easily moves over the mountain with its fucking thickness, then, as the ice melts due to global warming, it cannot move over the mountain easily, so it changes direction, this is evident in some of the erosional features it leaves behind."; x[76][1] = "";
        x[77][0] = "if ice has a positive budget, it will run over the sediments it deposits and make it all compact and aligned/oriented/orientation. if it is staying put, it creates a terminal moraine I believe, If the ice is receding, it leaves seidment in its wake and stuff"; x[77][1] = "";
        x[78][0] = "if the glacier dies, it means that it is no longer being fed, the ice will just melt and leave its sediments randomely deposited."; x[78][1] = "";
        x[79][0] = "Diamicton"; x[79][1] = "a collection of randomely sized grains, boulders, cobbles, fine grained, you name it. can be made by a landslide or glacier etc.";
        x[80][0] = "till"; x[80][1] = "sediment deposit left behind by glaciers";
        x[81][0] = "glacial outwash"; x[81][1] = "graded stream because it deposits coarse grained first and fine grained later. it begins braided because of the coarse grained sediment. called a valley train???";
        x[82][0] = "the meltwater current underneath a glacier in a lake can show"; x[82][1] = "glacial fluvial??";
        x[83][0] = "drop stones"; x[83][1] = "debris that falls out of the glacier or icebergs into a lake";
        x[84][0] = "glacial lacustrin deposit"; x[84][1] = "glacier deposits sediment in a lake";
        x[85][0] = "Varve:"; x[85][1] = "annual rhythmite. two thin layers of sediment, one dark and the other light in color, representing one year’s deposition in a lake";
        x[86][0] = "Rhythmites"; x[86][1] = "Rhythmically laminated sediment";
        x[87][0] = "in the summer I have a lot of melting off the glacier, lots of energy, water coming off top bottom of glacier brining sediment, lots of energy coarser grained sedimentation. in the winter we dont get as much melt off the glacier. lower energy lake environment where the finer particles can settle and become sediment. clay would be darker than silt, silt darker than sand"; x[87][1] = "";
        x[88][0] = "the glacier can deposit a varve that is a foot thick, and then the glacier retreats, and the varves will get thinner as the source of the sediment gets farther away."; x[88][1] = "";
        x[89][0] = "varves are a sign of glaciers, also a drop stone dammit."; x[89][1] = "";
        x[90][0] = "glaciolacustrine"; x[90][1] = "";
        x[91][0] = "flame structure in sediments"; x[91][1] = "in the bottom of lake I think? the sediments were disturbed by perhaps a drop stone or an earthquake.";
        x[92][0] = ""; x[92][1] = "";
        x[93][0] = ""; x[93][1] = "";
        x[94][0] = ""; x[94][1] = "";
        x[95][0] = ""; x[95][1] = "";
        x[96][0] = ""; x[96][1] = "";
        x[97][0] = ""; x[97][1] = "";
        x[98][0] = ""; x[98][1] = "";
        x[99][0] = ""; x[99][1] = "";
        x[100][0] = ""; x[100][1] = "";
        x[101][0] = ""; x[101][1] = "";
        x[102][0] = ""; x[102][1] = "";
        x[103][0] = ""; x[103][1] = "";
        x[104][0] = ""; x[104][1] = "";
        x[105][0] = ""; x[105][1] = "";
        x[106][0] = ""; x[106][1] = "";
        x[107][0] = ""; x[107][1] = "";
        x[108][0] = ""; x[108][1] = "";
        x[109][0] = ""; x[109][1] = "";
        x[110][0] = ""; x[110][1] = "";
        x[111][0] = ""; x[111][1] = "";
        x[112][0] = ""; x[112][1] = "";
        x[113][0] = ""; x[113][1] = "";
        x[114][0] = ""; x[114][1] = "";
        x[115][0] = ""; x[115][1] = "";
        x[116][0] = ""; x[116][1] = "";
        x[117][0] = ""; x[117][1] = "";
        x[118][0] = ""; x[118][1] = "";
        x[119][0] = ""; x[119][1] = "";
        x[120][0] = ""; x[120][1] = "";
        x[121][0] = ""; x[121][1] = "";
        x[122][0] = ""; x[122][1] = "";
        x[123][0] = ""; x[123][1] = "";
        x[124][0] = ""; x[124][1] = "";
        x[125][0] = ""; x[125][1] = "";
        x[126][0] = ""; x[126][1] = "";
        x[127][0] = ""; x[127][1] = "";
        x[128][0] = ""; x[128][1] = "";
        x[129][0] = ""; x[129][1] = "";
        x[130][0] = ""; x[130][1] = "";
        x[131][0] = ""; x[131][1] = "";
        x[132][0] = ""; x[132][1] = "";
        x[133][0] = ""; x[133][1] = "";
        x[134][0] = ""; x[134][1] = "";
        x[135][0] = ""; x[135][1] = "";
        x[136][0] = ""; x[136][1] = "";
        x[137][0] = ""; x[137][1] = "";
        x[138][0] = ""; x[138][1] = "";
        x[139][0] = ""; x[139][1] = "";
        x[140][0] = ""; x[140][1] = "";
        x[141][0] = ""; x[141][1] = "";
        x[142][0] = ""; x[142][1] = "";
        x[143][0] = ""; x[143][1] = "";
        x[144][0] = ""; x[144][1] = "";
        x[145][0] = ""; x[145][1] = "";
        x[146][0] = ""; x[146][1] = "";
        x[147][0] = ""; x[147][1] = "";
        x[148][0] = ""; x[148][1] = "";
        x[149][0] = ""; x[149][1] = "";
        x[150][0] = ""; x[150][1] = "";
        x[151][0] = ""; x[151][1] = "";
        x[152][0] = ""; x[152][1] = "";
        x[153][0] = ""; x[153][1] = "";
        x[154][0] = ""; x[154][1] = "";
        x[155][0] = ""; x[155][1] = "";
        x[156][0] = ""; x[156][1] = "";
        x[157][0] = ""; x[157][1] = "";
        x[158][0] = ""; x[158][1] = "";
        x[159][0] = ""; x[159][1] = "";
        x[160][0] = ""; x[160][1] = "";
        x[161][0] = ""; x[161][1] = "";
        x[162][0] = ""; x[162][1] = "";
        x[163][0] = ""; x[163][1] = "";
        x[164][0] = ""; x[164][1] = "";
        x[165][0] = ""; x[165][1] = "";
        x[166][0] = ""; x[166][1] = "";
        x[167][0] = ""; x[167][1] = "";
        x[168][0] = ""; x[168][1] = "";
        x[169][0] = ""; x[169][1] = "";
        x[170][0] = ""; x[170][1] = "";
        x[171][0] = ""; x[171][1] = "";
        x[172][0] = ""; x[172][1] = "";
        x[173][0] = ""; x[173][1] = "";
        x[174][0] = ""; x[174][1] = "";
        x[175][0] = ""; x[175][1] = "";
        x[176][0] = ""; x[176][1] = "";
        x[177][0] = ""; x[177][1] = "";
        x[178][0] = ""; x[178][1] = "";
        x[179][0] = ""; x[179][1] = "";
        x[180][0] = ""; x[180][1] = "";
        x[181][0] = ""; x[181][1] = "";
        x[182][0] = ""; x[182][1] = "";
        x[183][0] = ""; x[183][1] = "";
        x[184][0] = ""; x[184][1] = "";
        x[185][0] = ""; x[185][1] = "";
        x[186][0] = ""; x[186][1] = "";
        x[187][0] = ""; x[187][1] = "";
        x[188][0] = ""; x[188][1] = "";
        x[189][0] = ""; x[189][1] = "";
        x[190][0] = ""; x[190][1] = "";
        x[191][0] = ""; x[191][1] = "";
        x[192][0] = ""; x[192][1] = "";
        x[193][0] = ""; x[193][1] = "";
        x[194][0] = ""; x[194][1] = "";
        x[195][0] = ""; x[195][1] = "";
        x[196][0] = ""; x[196][1] = "";
        x[197][0] = ""; x[197][1] = "";
        x[198][0] = ""; x[198][1] = "";
        x[199][0] = ""; x[199][1] = "";
        x[200][0] = ""; x[200][1] = "";
        x[201][0] = ""; x[201][1] = "";
        x[202][0] = ""; x[202][1] = "";
        x[203][0] = ""; x[203][1] = "";
        x[204][0] = ""; x[204][1] = "";
        x[205][0] = ""; x[205][1] = "";
        x[206][0] = ""; x[206][1] = "";
        x[207][0] = ""; x[207][1] = "";
        x[208][0] = ""; x[208][1] = "";
        x[209][0] = ""; x[209][1] = "";
        x[210][0] = ""; x[210][1] = "";
        x[211][0] = ""; x[211][1] = "";
        x[212][0] = ""; x[212][1] = "";
        x[213][0] = ""; x[213][1] = "";
        x[214][0] = ""; x[214][1] = "";
        x[215][0] = ""; x[215][1] = "";
        x[216][0] = ""; x[216][1] = "";
        x[217][0] = ""; x[217][1] = "";
        x[218][0] = ""; x[218][1] = "";
        x[219][0] = ""; x[219][1] = "";
        x[220][0] = ""; x[220][1] = "";
        x[221][0] = ""; x[221][1] = "";
        x[222][0] = ""; x[222][1] = "";
        x[223][0] = ""; x[223][1] = "";
        x[224][0] = ""; x[224][1] = "";
        x[225][0] = ""; x[225][1] = "";
        x[226][0] = ""; x[226][1] = "";
        x[227][0] = ""; x[227][1] = "";
        x[228][0] = ""; x[228][1] = "";
        x[229][0] = ""; x[229][1] = "";
        x[230][0] = ""; x[230][1] = "";
        x[231][0] = ""; x[231][1] = "";
        x[232][0] = ""; x[232][1] = "";
        x[233][0] = ""; x[233][1] = "";
        x[234][0] = ""; x[234][1] = "";
        x[235][0] = ""; x[235][1] = "";
        x[236][0] = ""; x[236][1] = "";
        x[237][0] = ""; x[237][1] = "";
        x[238][0] = ""; x[238][1] = "";
        x[239][0] = ""; x[239][1] = "";
        x[240][0] = ""; x[240][1] = "";
        x[241][0] = ""; x[241][1] = "";
        x[242][0] = ""; x[242][1] = "";
        x[243][0] = ""; x[243][1] = "";
        x[244][0] = ""; x[244][1] = "";
        x[245][0] = ""; x[245][1] = "";
        x[246][0] = ""; x[246][1] = "";
        x[247][0] = ""; x[247][1] = "";
        x[248][0] = ""; x[248][1] = "";
        x[249][0] = ""; x[249][1] = "";
        x[250][0] = ""; x[250][1] = "";
        x[251][0] = ""; x[251][1] = "";
        x[252][0] = ""; x[252][1] = "";
        x[253][0] = ""; x[253][1] = "";
        x[254][0] = ""; x[254][1] = "";
        x[255][0] = ""; x[255][1] = "";
        x[256][0] = ""; x[256][1] = "";
        x[257][0] = ""; x[257][1] = "";
        x[258][0] = ""; x[258][1] = "";
        x[259][0] = ""; x[259][1] = "";
        x[260][0] = ""; x[260][1] = "";
        x[261][0] = ""; x[261][1] = "";
        x[262][0] = ""; x[262][1] = "";
        x[263][0] = ""; x[263][1] = "";
        x[264][0] = ""; x[264][1] = "";
        x[265][0] = ""; x[265][1] = "";
        x[266][0] = ""; x[266][1] = "";
        x[267][0] = ""; x[267][1] = "";
        x[268][0] = ""; x[268][1] = "";
        x[269][0] = ""; x[269][1] = "";
        x[270][0] = ""; x[270][1] = "";
        x[271][0] = ""; x[271][1] = "";
        x[272][0] = ""; x[272][1] = "";
        x[273][0] = ""; x[273][1] = "";
        x[274][0] = ""; x[274][1] = "";
        x[275][0] = ""; x[275][1] = "";
        x[276][0] = ""; x[276][1] = "";
        x[277][0] = ""; x[277][1] = "";
        x[278][0] = ""; x[278][1] = "";
        x[279][0] = ""; x[279][1] = "";
        x[280][0] = ""; x[280][1] = "";
        x[281][0] = ""; x[281][1] = "";
        x[282][0] = ""; x[282][1] = "";
        x[283][0] = ""; x[283][1] = "";
        x[284][0] = ""; x[284][1] = "";
        x[285][0] = ""; x[285][1] = "";
        x[286][0] = ""; x[286][1] = "";
        x[287][0] = ""; x[287][1] = "";
        x[288][0] = ""; x[288][1] = "";
        x[289][0] = ""; x[289][1] = "";
        x[290][0] = ""; x[290][1] = "";
        x[291][0] = ""; x[291][1] = "";
        x[292][0] = ""; x[292][1] = "";
        x[293][0] = ""; x[293][1] = "";
        x[294][0] = ""; x[294][1] = "";
        x[295][0] = ""; x[295][1] = "";
        x[296][0] = ""; x[296][1] = "";
        x[297][0] = ""; x[297][1] = "";
        x[298][0] = ""; x[298][1] = "";
        x[299][0] = ""; x[299][1] = "";
        String n;
        while(true){
            for(int i=0; i<length; i++){
                for(int j=0; j<2; j++){
                    System.out.print(x[z[i]][j]); 
                    n = user.nextLine();
                }
                System.out.println();
            }
        }
    }
}